name: Create S3 Static Site

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'feature/**'
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Region from tfvars
        run: |
          export REGION=$(grep 'region' infra/terraform.tfvars | cut -d'"' -f2)
          echo "Region: $REGION"
          echo "REGION=$REGION" >> $GITHUB_ENV

      - name: Set up AWS Cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Get Description from Pull Request
        run: |
          export DESCRIPTION=$(echo "${{ github.event.pull_request.body }}")
          echo "Description: $DESCRIPTION"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Get Bucket Name from tfvars
        run: |
          export BUCKET_NAME=$(cat infra/terraform.tfvars | grep bucket_name | cut -d'=' -f2 | tr -d '[:space:]')
          echo "Bucket Name: $BUCKET_NAME"
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV

      - name: Get Destroy Bucket from tfvars
        run: |
          export DESTROY_BUCKET=$(cat infra/terraform.tfvars | grep destroy_bucket | cut -d'=' -f2 | tr -d '[:space:]')
          echo "Destroy Bucket: $DESTROY_BUCKET"
          echo "DESTROY_BUCKET=$DESTROY_BUCKET" >> $GITHUB_ENV
 
      - name: Destroy Bucket if variable is set
        if: ${{ env.DESTROY_BUCKET == 'true' }}
        run: |
          aws s3api delete-bucket --bucket ${{ env.BUCKET_NAME }} --region us-east-1 || true

      - name: Create Bucket if variable is not set
        if: ${{ env.DESTROY_BUCKET != 'true' }}
        run: |
          aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --region us-east-1
          aws s3 website s3://${{ env.BUCKET_NAME }} --index-document index.html --error-document error.html

      - name: Set PR msg
        run: |
          echo "MSG=O bucket ${{ env.BUCKET_NAME }} foi ${{ env.DESTROY_BUCKET == 'true' && 'destruído' || 'criado' }} com sucesso!" >> $GITHUB_ENV

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: ${{ github.event.pull_request.number }},
              repo: context.repo.repo,
              body: `${{ env.MSG }}`
            })
