name: Create S3 Statis Site

on:
  pull_request:
    types: opened
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Description from Issue
        run: |
          export DESCRIPTION=$(echo "${{ github.event.issue.body }}")
          echo "Description: $DESCRIPTION"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Destroy Bucket if variable is set
        if: ${{ env.DESTROY_BUCKET == 'true' }}
        run: |
          aws s3api delete-bucket --bucket ${{ github.event.issue.number }} --region us-east-1 || true
        env:
          BUCKET_NAME: ${{ github.event.issue.number }}
          
      - name: Create Bucket if variable is not set
        if: ${{ env.DESTROY_BUCKET != 'true' }}
        run: |
          aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --region us-east-1
          aws s3api put-bucket-policy --bucket ${{ env.BUCKET_NAME }} --policy file://infra/s3-static-website/policy.json
          aws s3 website s3://${{ env.BUCKET_NAME }} --index-document index.html --error-document error.html
        env:
          BUCKET_NAME: ${{ github.event.issue.number }}      
      
      - name: Add Comment
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: >
            O bucket ${{ env.BUCKET_NAME }} 
            foi ${{ env.DESTROY_BUCKET == 'true' && 'destruído' || 'criado' }} com sucesso!
